apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter-notebook
  namespace: jonas
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: jupyter.example.org
    http:
      paths:
      - backend:
          serviceName: jupyter-notebook
          servicePort: 80

